@startuml
title ユーザーが本を借りるフロー

|ブラウザー|
|システム|

|ブラウザー|
start
:本を選ぶ;
:「借りる」ボタン押す;
|システム|
if (ユーザーが既に借りている？) then (no)
    if (ユーザーのお金足りる？) then (no)
        :エラー;
        stop
    else (yes)
        :ユーザーのお金から本の貸し出し金額を引く;
        :貸し出し期間を現在から７日後に設定;
        :貸し出し履歴に追加;
        stop
    endif
else (yes)
    :エラー;
    stop
endif
@enduml
