@startuml
title ユーザーが本を借りるフロー

|ブラウザー|
|システム|

|ブラウザー|
start
:本を選ぶ;
:「レンタル開始」ボタン押す;
:APIリクエスト送信;
|システム|

:APIリクエストからデータ抽出
- ユーザー名
- 指定の本;
:app_user_book_rental_current
のテーブルからユーザーのデータ取得;
if (取得したデータの中に指定の本がある) then (ある)
    :エラー
    既にレンタル中です。;
    stop
else (ない)
endif

:book_price
のテーブルから指定の本のデータ取得;
if (取得したデータが空) then (空)
    :エラー
    本が見つかりません。;
    stop
else (空じゃない)
endif

:app_user
のテーブルからユーザーのデータ取得;
if (取得したデータが空) then (空)
    :エラー
    ユーザーがみつかりません。;
    stop
else (空じゃない)
endif

if (ユーザーのお金が指定の本の貸し出し金額以上) then (未満)
    :エラー
    お金が足りない;
    stop
else (以上)
endif

:ユーザーのお金から本の貸し出し金額分を引く;
:app_userのテーブルに
変更後のユーザーの金額を保存する;
:指定の本のレンタル開始日時を今に設定;
:指定の本のレンタル終了日時を今から７日後に設定;
:app_user_book_rental_current
のテーブルにデータを追加
- ユーザー
- 指定の本
- レンタル開始日
- レンタル終了日;
:app_user_book_rental_history
のテーブルにデータを追加
- ユーザー
- 指定の本
- レンタル開始日
- レンタル終了日;
:メールの送り主をnoreply@sample-solid.comに設定;
:メールの送り先をユーザーのメールアドレスに設定;
:メールのサブジェクトを設定;
:メールの本文を設定;
:メールを送信;
stop
@enduml
