@startuml
title 本のレンタル開始フロー

|ブラウザー|
|システム|

|ブラウザー|
start
:本を選ぶ;
:「レンタル開始」ボタン押す;
|システム|

if (既にレンタル中) then (yes)
    :エラー;
    stop
else (no)
    if (ユーザーのお金が足りていない) then (yes)
        :エラー;
        stop
    else (no)
        :ユーザーのお金から貸し出し金額分を引く;
        :本のレンタル期間を今から７日間に設定;
        :ユーザーのレンタル履歴の更新;
        :ユーザーにレンタル完了のメール通知;
        stop
    endif
endif
@enduml
