@startuml
title 本を返すフロー

|定期実行サービス|
|システム|

|定期実行サービス|
start
:一時間に一回実行;

|システム|
:すべての本の貸し出し期間チェック;
if (貸し出し期間が過ぎている) then (no)
    :なにもしない;
    stop
else (yes)
    :貸出中から貸し出し履歴に変更;
    stop
endif
@enduml
