@startuml
title Single responsibility

package controller <<責任：HTTPの処理>> {
    class BookRentalController {
        責任：本のレンタル関連のAPIの処理
        + rentBook()
    }
}

package service <<責任：ビジネスロジックとデータのつなぎ合わせ>> {
    class BookRentalService {
    + rentBook()
    }

    class UserNotificationService {
    + notifyUser()
    }
}

package repository <<責任：DB関連の処理>> {
    class BookRepository {
    + findPriceById()
    }

    class UserBookRentalRepository {
    + findByUsername()
    }

    class UserRepository {
    + findByUsername()
    }
}

package core <<責任：ビジネスロジックの処理>> {
    class UserBookRentalModel {
    + rentBook()
    }
}

BookRentalController ..> BookRentalService: uses
BookRentalService ..> BookRepository: uses
BookRentalService ..> UserRepository: uses
BookRentalService ..> UserBookRentalRepository: uses
UserNotificationService ..> UserRepository: uses
UserNotificationService <. BookRentalService: uses
BookRentalService .> UserBookRentalModel: uses

@enduml
